### ISSUE TITLE
no upgrade option in game

### ISSUE THREAD

**Issue by amzeus1976** [WeakAuras/WeakAuras-Companion#81]
the companion out side of game is list two addons due for upgrade (there are more but thats another bug)
in game there is no marks, tried reload,restarting

**Comment by mrbuds** [comment]
**Operating System:**
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
can't help without answer to these questions, i'm going to close this ticket
