### ISSUE TITLE
Companion showing updates for auras I already applied in-game. WeakAuras also not giving me an option to "update" the aura in-game. Just import as duplicate.

### ISSUE THREAD

**Issue by NANTOIANER** [WeakAuras/WeakAuras-Companion#855]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux
**Companion Version:**
3.0.6
**WeakAuras Version:**
3.0.5
**Companion App Console Log:** 
app.472327b7.js:1 validateWowpath
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 buildVersionList
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_#NANTOIANER-20201103185412.zip saved
**WeakAuras Errors:**
None
**Describe the bug**
Companion shows 4 available updates, even after restarting Companion and WoW multiple times. Two of these updates were already applied. The other two show up in-game (as they should), but I do not get the option to import these updates "as updates". Only get the option to important them (as duplicates).
**To Reproduce**
Hit "fetch updates".
Go in-game and open WeakAuras panel.
Try hitting the white "update" icon.
Only get an option to import as duplicate.
**Expected behavior**
Companion should only show updates that haven't been applied, yet. And I should get an option to import auras as updates.
**Screenshots**
![WeakAuras_Companion_qJctZYAXcL](https://user-images.githubusercontent.com/73881929/98023926-e45f7e80-1e07-11eb-9408-3c74ee9fdfa4.png)
![WeakAuras_Companion_jSGmTGW48I](https://user-images.githubusercontent.com/73881929/98023929-e6294200-1e07-11eb-9089-97cf9a21b715.png)
![Wow_UAd41uBlAI](https://user-images.githubusercontent.com/73881929/98023935-e75a6f00-1e07-11eb-846d-5c6693b601e7.png)
![Wow_H8rc1Vh3Qa](https://user-images.githubusercontent.com/73881929/98023940-e88b9c00-1e07-11eb-9226-82d295c2ba1a.png)
![Wow_SIgLt0QADy](https://user-images.githubusercontent.com/73881929/98024226-491ad900-1e08-11eb-8f5c-b9a574a1e54a.png)
![Wow_5DVtQmUBqp](https://user-images.githubusercontent.com/73881929/98024230-4ae49c80-1e08-11eb-8f9c-03af64ff4a58.png)
![Wow_iSlR1IghuH](https://user-images.githubusercontent.com/73881929/98023950-eaedf600-1e07-11eb-8042-dd23a633d710.png)
**config.json**
[configJSON.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5483157/configJSON.zip)
**WeakAuras.lua**
[WeakAurasLUA.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5483159/WeakAurasLUA.zip)

edit: Added more screenshots.

**Comment by mrbuds** [comment]
Can't investigate without your data

**Comment by mrbuds** [comment]
I'm blind xD

**Comment by NANTOIANER** [comment]
Seems like resetting the cache did the trick. Sorry for wasting your time. :sweat:

**Comment by bentsku** [comment]
Thanks again for reporting!

To keep track of the error, I think I know where it comes from.

When we fetch the auras informations from wago.io, we then look over the results to know which one we should fetch the encoded string for.
https://github.com/WeakAuras/WeakAuras-Companion/blob/871e6612b318648224874daaf07f6419fe9ead3b/src/components/LandingPage.vue#L1420-L1432

We then set the wagoVersion property to the wagoData.version.
https://github.com/WeakAuras/WeakAuras-Companion/blob/871e6612b318648224874daaf07f6419fe9ead3b/src/components/LandingPage.vue#L1447

But a failure happen when we fetch the encoded string, the wagoVersion stays, and we won't fetch this aura again until the next update, because of the condition for which we will fetch auras (we need the wagoData.version > aura.version && wagoData.version > aura.wagoversion).

I've checked, and in the config.json, the wagoVersion is indeed `1.0.13-34`
But the encoded string is not the same as the one you can copy on wago for this version. I guess it could be the reason.

I can try to work a quick fix while I work on the refactoring.
